### ISSUE TITLE
Problem with the rotation helper

### ISSUE THREAD

**Issue by Critzie** [Elysia-ff/FFXIV_RotationHelper#2] opened 2019-05-19 06:39 UTC
Some role actions and abilities don't circle through the rotation and end up getting stuck even though the said role action or ability is used

**Comment by Elysia-ff** [comment] 2019-05-20 08:56
Yeah, I could make some mistakes with action code. I'm finding what's wrong, but It'll take a few time due to the number.

**Comment by Critzie** [comment] 2019-05-26 03:23
Did you get any progress with the problem?

**Comment by Elysia-ff** [comment] 2019-05-26 12:41
Most skills of PLD 70, WHM 64, SCH 70, AST 64, DRG 61, SAM 70, BRD 70, MCH 70, BLM 70, RDM 70 and their cross skills worked fine.
Can you specify the skills which make it stuck?

ps. Skills of Gatherer and Crafter may not be working, also potions either. (e.g Potion of Dexterity)

**Comment by Critzie** [comment] 2019-05-26 17:26
Its is Potion, Mirage Dive, and Diversion I had problems with

**Comment by Elysia-ff** [comment] 2019-05-27 12:10
Don't include the potions in the rotation. The potions in the ffxivrotations.com and in-game one don't match one-on-one. It's not working properly.

Mirage Dive and Diversion worked well for me. (tested on HoH)
Plz try again with the latest version and make sure the logs are being written correctly.

> For Mirage Dive, Search '|1CE7|'
21|2019-05-27T19:59:55.3020000+09:00|100D3D81|Ellie|1CE7|환영 강타|40015ABB|

> For Diversion, Search '|1D79|'
21|2019-05-27T19:59:19.0380000+09:00|100D3D81|Ellie|1D79|주의 전환|100D3D81|

If you couldn't find anything, can you give me the log file and your rotation url?

**Comment by Critzie** [comment] 2019-05-30 02:12
Just tested again and Mirage Dive and Diversion doesn't move
Also, is there a way for the abilities to not move through the rotations so like a still image

**Comment by Elysia-ff** [comment] 2019-05-30 09:25
Check the log file please?
because It's not reproducible for me, I can't help you without any clue.

**Comment by Critzie** [comment] 2019-05-31 01:49
[Network_20190531.zip](https://github.com/Elysia-ff/FFXIV_RotationHelper/files/3239347/Network_20190531.zip)

Here i hope that is the logs you need

**Comment by Elysia-ff** [comment] 2019-05-31 11:59
Unfortunately, There are action codes for Mirage Dive and Diversion.

> 21|2019-05-31T03:46:02.4650000+02:00|106BE569|Jack Mirakuru|1CE7|Mirage Dive|4000079F|Striking Dummy|

> 21|2019-05-31T03:44:33.2020000+02:00|106BE569|Jack Mirakuru|1D79|Diversion|106BE569|Jack Mirakuru|

It means, If you used them while the plugin is working, It should've worked.
I'm finding if there is a bug or something,
Could you give me more information to find what's wrong?

1. The URL that you're trying.
2. Could you make a video contains wrong situation? (don't have to do this, but this is more helpful than (1).)

Thanks.

**Comment by Critzie** [comment] 2019-06-01 01:17
This is with Diversion
https://www.youtube.com/watch?v=RBSRIv_W35E
http://ffxivrotations.com/201r 

This is with Mirage Dive 
https://www.youtube.com/watch?v=BdjpAgWQlqo
http://ffxivrotations.com/21oc

**Comment by Elysia-ff** [comment] 2019-06-04 15:18
Nothing special found yet. There are 2 reasons which may can cause your problem.
1. The plugin couldn't read some action logs from FFXIV_ACT_PlugIn. (diversion and mirage dive in your case.)
2. Read action logs successfully, but plugin won't work.

Like I said, This is not reproducible, so I'll give you debug version plugin. ([FFXIV_RotationHelper.zip](https://github.com/Elysia-ff/FFXIV_RotationHelper/files/3253070/FFXIV_RotationHelper.zip))

This has a log section below.
![image](https://user-images.githubusercontent.com/45890606/58890496-b020f380-8725-11e9-830a-a1529d17eafd.png)

Play the same rotation(not working expected) and Just Copy-paste it here.
Sorry for taking long time.

**Comment by Elysia-ff** [comment] 2019-07-12 10:17
Close this issue because no more responding long time and all action codes will be reworked for ShB.

**Closed as completed by Elysia-ff** 2019-07-12 10:17 UTC
