### ISSUE TITLE
Some abilities not reflected in skill rotation

### ISSUE THREAD

**Issue by SecondReality** [Elysia-ff/FFXIV_RotationHelper#7] opened 2020-05-31 16:46 UTC
Hello - I'm the developer who made the ffxivrotations site - I'm posting this on behalf of a ffxivrotations.com user.

> About the Summoner. 
When I rotated this skill, some abilities were not reflected in the skill rotation.
I think the reason for this is that pet hits are slow and abilities are judged too quickly.
It would be great if you could fix this problem as well, since the higher level players are inserting abilities between GCDs.
My rotations: http://ffxivrotations.com/2rlz
Energy Drain missing: https://youtu.be/FMmodBL9PwQ
Fester hit early: https://youtu.be/XKAVxNO5V0c
Thanks,

**Comment by Elysia-ff** [comment] 2021-04-21 12:55
Duplicate of #5

**Closed as completed by Elysia-ff** 2021-04-21 12:55 UTC
