### ISSUE TITLE
does not work

### ISSUE THREAD

**Issue by Sephixx** [Elysia-ff/FFXIV_RotationHelper#6] opened 2020-03-10 09:29 UTC
does not work with new Shadowbringers spells.
tested with the machinist, the monk, the drk.

**Comment by Sephixx** [comment] 2020-03-11 13:34
machinist's spells that don't work: 
- Drill
- Heated Split Shot
- Barrel Stabilizer
- Heated Slug Shot
- Air Anchor
- Heated Clean Shot
- Hypercharge
- Heat Blast

**Comment by Elysia-ff** [comment] 2021-04-21 12:56
Duplicate of #5

**Closed as completed by Elysia-ff** 2021-04-21 12:56 UTC
